=== ritabokach/BokachPIN252t/tasks/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="world_architecture">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="country" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="architect" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="building" maxOccurs="unbounded"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="building">
    <xs:complexType>
      <xs:attribute name="year" type="xs:string" use="required"/>
      <xs:attribute name="height" type="xs:string" use="optional"/>
      <xs:attribute name="type" type="xs:string" use="optional"/>
      <xs:attribute name="status" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ritabokach/BokachPIN252t/tasks/buildings.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="buildings.xsl"?>
<world_architecture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="buildings.xsd"
                    version="2.0">

  <!-- Франция -->
  <country id="Франция">
    <architect name="Гюстав Эйфель">
      <building code="Эйфелева башня" year="1889" photo="images\eiffel_tower.jpeg"/>
    </architect>
  </country>

  <!-- Италия -->
  <country id="Италия">
    <architect name="Филиппо Брунеллески">
      <building code="Купол флорентийского Собора" year="1471" photo="images\duomo.jpeg"/>
    </architect>
    <architect name="Джованни Лоренцо Бернини">
      <building code="Площадь Святого Петра" year="1667" photo="images\St_Peter's_Square.jpeg"/>
    </architect>
  </country>

  <!-- Индия -->
  <country id="Индия">
    <architect name="Устад Ахмад Лахаури">
      <building code="Тадж-Махал" year="1653" photo="images\taj-mahal.jpeg"/>
    </architect>
  </country>

  <!-- Испания -->
  <country id="Испания">
    <architect name="Антонио Гауди">
      <building code="Саграда Фамилия" year="1882" photo="images\sagrada.jpeg"/>
    </architect>
  </country>

  <!--Германия-->
  <country id="Россия">
    <architect name="Огюст Монферран">
        <building code="Исаакиевский собор" year="1858" photo="images\St_Isaacs_Cathedral.jpeg"/>
    </architect>
  </country>

</world_architecture>
